parameters:

    #
    # Factories
    #
    elcodi.factory.image.class: Elcodi\Component\Media\Factory\ImageFactory

    #
    # Services
    #
    elcodi.core.media.resize.imagemagick.class: Elcodi\Component\Media\Adapter\Resizer\ImageMagickResizeAdapter
    elcodi.manager.media_image.class: Elcodi\Component\Media\Services\ImageManager
    elcodi.manager.media_file.class: Elcodi\Component\Media\Services\FileManager
    elcodi.image_uploader.class: Elcodi\Component\Media\Services\ImageUploader

    #
    # Controllers
    #
    elcodi.controller.media_image_resize.class: Elcodi\Component\Media\Controller\ImageResizeController
    elcodi.controller.media_image_upload.class: Elcodi\Component\Media\Controller\ImageUploadController

    #
    # Routes
    #
    elcodi.router.media_image_resize.class: Elcodi\Component\Media\Router\ImageResizeRouterLoader
    elcodi.router.media_image_view.class: Elcodi\Component\Media\Router\ImageViewRouterLoader
    elcodi.router.media_image_upload.class: Elcodi\Component\Media\Router\ImageUploadRouterLoader

    #
    # Twig extensions
    #
    elcodi.twig_extension.media_image.class: Elcodi\Component\Media\Twig\ImageExtension

    #
    # Transformers
    #
    elcodi.transformer.media_image_etag.class: Elcodi\Component\Media\Transformer\ImageEtagTransformer
    elcodi.transformer.media_file_identifier.class: Elcodi\Component\Media\Transformer\FileIdentifierTransformer

    #
    # Event Dispatchers
    #
    elcodi.event_dispatcher.media.class: Elcodi\Component\Media\EventDispatcher\MediaEventDispatcher