services:

    #
    # Controllers
    #
    elcodi.core.media.controllers.image_resize:
        class: %elcodi.core.media.controllers.image_resize.class%
        calls:
            - [setObjectManager, [@doctrine.orm.entity_manager]]
            - [setImageNamespace, [%elcodi.core.media.entity.image.class%]]
            - [setFilesystem, [@elcodi.core.media.filesystem.default]]
            - [setFileTransformer, [@elcodi.core.media.transformer.file]]
            - [setResizeAdapter, [@elcodi.core.media.resize.default]]

    elcodi.core.media.controllers.image_upload:
        class: %elcodi.core.media.controllers.image_upload.class%
        calls:
            - [setObjectManager, [@doctrine.orm.entity_manager]]
            - [setImageManager, [@elcodi.core.media.services.image_manager]]
            - [setFileManager, [@elcodi.core.media.services.file_manager]]
            - [setFieldName, [%elcodi.core.media.image_upload_field_name%]]