services:

    #
    # Factories
    #

    #
    # Factory for entity image
    #
    elcodi.factory.image:
        class: %elcodi.factory.image.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.media.entity.image.class%"]]
