services:

    #
    # Object Managers
    #
    elcodi.object_manager.image:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            cart_namespace: %elcodi.core.media.entity.image.class%
