services:

    #
    # Repositories
    #

    #
    # Repository for entity image
    #
    elcodi.repository.image:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.media.entity.image.class%
