services:

    #
    # Repositories
    #

    #
    # Repository for entity image
    #
    elcodi.core.media.repository.image:
        class: %elcodi.core.media.repository.image.class%
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.media.entity.image.class%

    elcodi.repository.image:
        alias: elcodi.core.media.repository.image
