services:

    #
    # Repositories
    #

    #
    # Repository for entity image
    #
    elcodi.repository.image:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.media.entity.image.class% ]
