services:

    #
    # Transformers
    #
    elcodi.transformer.media_image_etag:
        class: %elcodi.transformer.media_image_etag.class%

    elcodi.transformer.media_file_identifier:
        class: %elcodi.transformer.media_file_identifier.class%
