services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.media_image:
        class: %elcodi.twig_extension.media_image.class%
        arguments:
            - @router
            - %elcodi.core.media.image_resize_controller_route_name%
            - %elcodi.core.media.image_view_controller_route_name%
        tags:
            - { name: twig.extension }
